# Generated by Django 4.2.3 on 2023-08-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
