# Generated by Django 4.2.3 on 2023-08-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id']},
        ),
    ]
