# Generated by Django 4.2.3 on 2023-08-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_employee_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date',
            new_name='age',
        ),
    ]
