# Generated by Django 4.2.3 on 2023-08-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_date_employee_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='image',
            new_name='profile_image',
        ),
    ]
