# Generated by Django 4.2.3 on 2023-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_image_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='resume/'),
        ),
    ]
