# Generated by Django 4.2.2 on 2023-08-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employee_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(default=None, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.FileField(default=None, null=True, upload_to='media/'),
        ),
    ]
