# Generated by Django 4.2.2 on 2023-08-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_employee_cv_alter_employee_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.DateField(),
        ),
    ]
