# Generated by Django 4.2.2 on 2023-08-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_employee_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='age',
            new_name='dob',
        ),
    ]
